/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormRelatorioTimes.java
 *
 * Created on 16/02/2012, 21:13:53
 */

package view;

import business.TimeBS;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author helder
 */
public class FormRelatorioTimes extends javax.swing.JFrame {

    /** Creates new form FormRelatorioTimes */
    public FormRelatorioTimes() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Executar Relatório");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jButton1)
                .addContainerGap(180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jButton1)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
  try{
    TimeBS timeBS = new TimeBS();

    JRResultSetDataSource jrRS = timeBS.retornarRelatorio();
    /* HashMap de parametros utilizados no relatÃ³rio. Sempre instanciados */
    Map parameters = new HashMap();
    //parameters.put("nome", "teste");
    /* Preenche o relatÃ³rio com os dados. Gera o arquivo BibliotecaPessoal.jrprint */
    JasperPrint impressao = JasperFillManager.fillReport("c:\\teste\\campeonatoreport.jasper" , parameters,    jrRS );
    //exibe o resultado
    JasperViewer viewer = new JasperViewer( impressao , true );
    viewer.setVisible(true);
    //	viewer.show();
        }
  catch (Exception e){




    }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRelatorioTimes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

}
